---
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: example-crontab
spec:
  cronSpec: "* * * * /5"
  image: my-awesome-cron-image
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  conversion:
    strategy: None
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
      - ct
  versions:
    - name: v1
      served: true
      storage: true
